FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    autoconf \
    automake \
    libtool \
    git \
    pkg-config \
    time \
    mosquitto \
    mosquitto-clients \
    libmosquitto-dev \
    libcjson-dev

# RUN apt-get install -y libssl-dev

WORKDIR /app
