FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    autoconf \
    automake \
    libtool \
    git \
    pkg-config \
    time \
    mosquitto \
    mosquitto-dev

WORKDIR /app
